services:
  client-service:
    build:
      context: ./software
      dockerfile: rpi.Dockerfile
    environment:
        MQTT_ENDPOINT: 192.168.178.28
        MQTT_PORT: 1883
    devices:
      - /dev/video0
#      - /dev/gpiomem
