services:
  pc-service:
    image: ${DOCKER_REGISTRY}/pc-app:latest
    build:
      context: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./yolov8n_100e.pt:/yolomodel.pt:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - MQTT_ENDPOINT=${MQTT_ENDPOINT}
      - MQTT_PORT=${MQTT_PORT}
      
