services:
  pc-service:
    image: ${DOCKER_REGISTRY}/pc-app:latest
    build:
      context: .
    volumes:
      - ./yolov8n_100e.pt:/yolomodel.pt:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - MQTT_ENDPOINT=${MQTT_ENDPOINT}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - IS_DOCKER=true
