version: '3'
services:
  # https://community.home-assistant.io/t/mosquitto-allow-local-network-access/284833/13
  mosquitto:
    command: "mosquitto -c /mosquitto-no-auth.conf"
    image: eclipse-mosquitto
    environment:
      - TZ
    ports:
      - "1883:1883"
      - "9001:9001"
    user: 1000:1000
    volumes:
      - "./config:/mosquitto/config"
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
