services:
  rpi-service:
    image: ${DOCKER_REGISTRY}/rpi-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MQTT_ENDPOINT=${MQTT_ENDPOINT}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    devices:
      - /dev/video0
#      - /dev/gpiomem
