name: Docker CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push pc_app
        uses: docker/build-push-action@v6
        with:
          context: ./pc_app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/pc-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/pc-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/pc-app:buildcache,mode=max

      - name: Build and push rpi_app
        uses: docker/build-push-action@v6
        with:
          context: ./rpi_app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/rpi-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/rpi-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/rpi-app:buildcache,mode=max
